# https://git-cliff.org/docs/configuration
# https://keats.github.io/tera/docs/#introduction

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""

body = """
{% if version -%}
  ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
  ## [Unreleased]
{% endif %}
{% for group, commits in commits | group_by(attribute="group") -%}
  ### {{ group | striptags }}

  {% for commit in commits -%}
    - {{ commit.message }}
  {% endfor %}
{% endfor %}
"""

footer = """
{% set repo_url = "https://github.com/" ~ remote.github.owner ~ "/" ~ remote.github.repo -%}
{% for release in releases -%}
  {% if release.version -%}
    {% if release.previous.version -%}
      [{{ release.version | trim_start_matches(pat="v") }}]: {{ repo_url }}/compare/{{ release.previous.version }}..{{ release.version }}
    {% else -%}
      [{{ release.version | trim_start_matches(pat="v") }}]: {{ repo_url }}/tag/{{ release.version }}
    {% endif -%}
  {% else -%}
    {% if release.previous.version -%}
      [Unreleased]: {{ repo_url }}/compare/{{ release.previous.version }}..HEAD
    {% else -%}
      [Unreleased]: {{ repo_url }}
    {% endif -%}
  {% endif -%}
{% endfor %}
"""

trim = true



[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->Features" },
  { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
  { message = "^docs", group = "<!-- 2 -->Documentation" },
  { message = "^perf", group = "<!-- 3 -->Performance" },
  { message = "^refactor", group = "<!-- 4 -->Refactor" },
  { message = "^style", group = "<!-- 5 -->Styling" },
  { message = "^test", group = "<!-- 6 -->Testing" },
  { message = "^revert", group = "<!-- 7 -->Revert" },
  { message = "^(build|chore|ci)", skip = true },
]
tag_pattern = "v[0-9].*"



[remote.github]
owner = "zenekron"
repo = "zecomi"
